name: Restart Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: verify deployment
      uses: steebchen/kubectl@v2.0.0
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        version: v1.21.0 # specify kubectl binary version explicitly
        command: kubectl rollout restart deployment.apps/tenant-ui
